enable_color: true
enable_depth: true
enable_infra: false
enable_infra1: false
enable_infra2: false
enable_gyro: false
enable_accel: false
enable_sync: false
enable_pointcloud: true
align_depth: true
color_width: 640
color_height: 480
color_fps: 30
depth_width: 640
depth_height: 480
depth_fps: 30
publish_tf: true
tf_publish_rate: 0.0
publish_odom_tf: false
reconnect_timeout: 6.0
wait_for_device_timeout: 10.0
